export const copy = {
  th: {
    title: 'Agent Console', subtitle: 'ดูงานของเอเจนต์ คำขออนุมัติ และเอเจนต์ภายนอกที่เชื่อมต่อในโปรเจกต์นี้',
    tabs: { timeline: 'งานของเอเจนต์', approvals: 'คำขออนุมัติ', agents: 'เอเจนต์ที่เชื่อมต่อ', connect: 'เชื่อมต่อ MCP / A2A' },
    copy: 'คัดลอก', copied: 'คัดลอกแล้ว', copyFailed: 'คัดลอกไม่สำเร็จ กรุณาเลือกข้อความแล้วคัดลอกเอง',
    opaction: 'ไม่สามารถดำเนินการได้ ลองโหลดสถานะใหม่',
    // timeline
    ops: { evaluate_job: 'ประเมินงาน', draft_documents: 'ร่างเอกสาร', export_document: 'สร้างไฟล์เอกสาร', profile_cv: 'วิเคราะห์ CV', match_jobs: 'จัดอันดับงานด้วย AI' },
    filters: { all: 'ทั้งหมด', active: 'กำลังทำ', waiting: 'รออนุมัติ', done: 'เสร็จ', failed: 'ล้มเหลว' },
    cols: { op: 'งาน', job: 'ตำแหน่ง', status: 'สถานะ', created: 'เริ่มเมื่อ', duration: 'ใช้เวลา', score: 'คะแนน', session: 'เซสชัน' },
    running: 'กำลังทำงาน', untitled: 'งานไม่มีชื่อ', openSession: 'เปิดเซสชัน', retry: 'ลองใหม่', retryOf: 'ลองใหม่จากงานก่อนหน้า',
    noRuns: 'ยังไม่มีงานของเอเจนต์', noRunsNext: 'ประเมินงานหรือร่างเอกสาร งานจะแสดงที่นี่', noMatch: 'ไม่มีงานในสถานะนี้', autoRefresh: 'รีเฟรชอัตโนมัติทุก 5 วินาทีขณะมีงานที่ยังทำอยู่', filterLabel: 'กรองตามสถานะ',
    // approvals
    actions: { promote_cv: 'ใช้ CV ฉบับใหม่เป็นฉบับหลัก', delete_document_revision: 'ลบเอกสารฉบับนี้', delete_file: 'ลบไฟล์นี้' },
    pending: 'รอการตัดสินใจ', resolved: 'ตัดสินใจแล้ว', approve: 'อนุมัติ', reject: 'ปฏิเสธ', expiresIn: 'หมดอายุ', openRun: 'ดูงานที่ขอ', digest: 'ลายนิ้วมือการเปลี่ยนแปลง',
    approved: 'อนุมัติแล้ว', rejected: 'ปฏิเสธแล้ว', expired: 'หมดอายุ', used: 'ใช้แล้ว', noPending: 'ไม่มีคำขอที่รออนุมัติ', noApprovals: 'ยังไม่มีคำขออนุมัติ', noApprovalsNext: 'เมื่อเอเจนต์ต้องการเปลี่ยนแปลงสำคัญ คำขอจะแสดงที่นี่',
    // agents
    caps: { 'results:read': 'อ่านผลลัพธ์', 'jobs:evaluate': 'ประเมินงาน', 'documents:draft': 'ร่างเอกสาร' },
    grants: 'สิทธิ์ที่ออกไว้', noGrants: 'ยังไม่มีเอเจนต์ภายนอกเชื่อมต่อ', noGrantsNext: 'ออก access token เพื่อให้ MCP client หรือเอเจนต์อื่นเข้าถึงโปรเจกต์นี้',
    active: 'ใช้งานอยู่', expiredS: 'หมดอายุ', revoked: 'เพิกถอนแล้ว', expiresAt: 'หมดอายุ', revoke: 'เพิกถอน', token: 'Access token', issue: 'ออก access token', issueIntro: 'เลือกสิทธิ์และอายุของ token สำหรับเอเจนต์ภายนอก',
    capabilities: 'สิทธิ์', expiry: 'อายุ', h1: '1 ชั่วโมง', h24: '24 ชั่วโมง', d7: '7 วัน', create: 'ออก token', shownOnce: 'Token ของคุณ',
    warning: 'คัดลอกเก็บไว้ตอนนี้ ระบบจะไม่แสดงอีก', dismiss: 'ปิดและลบออกจากหน้านี้', needCap: 'เลือกอย่างน้อยหนึ่งสิทธิ์', id: 'สิทธิ์',
    // connect
    connectTitle: 'เชื่อมต่อ MCP / A2A', connectIntro: 'โปรเจกต์นี้เปิดให้ MCP client และเอเจนต์ A2A ภายนอกเรียกใช้ได้ผ่าน protocol listener ซึ่งปิดอยู่เป็นค่าเริ่มต้น เปิดเมื่อต้องการเท่านั้น',
    startTitle: 'เริ่ม listener', startNote: 'ต้องเริ่มแอปด้วย --enable-sharing จึงจะเปิดพอร์ตนี้',
    endpoints: 'ปลายทาง', mcp: 'MCP (streamable HTTP)', card: 'Agent card', a2a: 'A2A base URL',
    snippetTitle: 'ตั้งค่า MCP client', snippetNote: 'แทน <ACCESS_TOKEN> ด้วย token จากแท็บ "เอเจนต์ที่เชื่อมต่อ" ห้ามฝัง token จริงในไฟล์ที่แชร์หรือ commit',
    curlTitle: 'ตรวจ agent card ด้วย curl', secNote: 'Token เป็น bearer credential ใครถือ token ก็เข้าถึงโปรเจกต์ตามสิทธิ์ได้ เก็บเป็นความลับ ตั้งอายุให้สั้น และเพิกถอนเมื่อไม่ใช้',
  },
  en: {
    title: 'Agent Console', subtitle: 'Review agent tasks, approval requests and external agents connected to this project',
    tabs: { timeline: 'Task timeline', approvals: 'Approval inbox', agents: 'Connected agents', connect: 'Connect MCP / A2A' },
    copy: 'Copy', copied: 'Copied', copyFailed: 'Could not copy. Select the text and copy it manually.',
    opaction: 'Could not complete the action. Status reloaded.',
    ops: { evaluate_job: 'Evaluate job', draft_documents: 'Draft documents', export_document: 'Generate file', profile_cv: 'Analyze CV', match_jobs: 'Rank jobs with AI' },
    filters: { all: 'All', active: 'In progress', waiting: 'Needs approval', done: 'Done', failed: 'Failed' },
    cols: { op: 'Task', job: 'Job', status: 'Status', created: 'Started', duration: 'Duration', score: 'Score', session: 'Session' },
    running: 'Running', untitled: 'Untitled job', openSession: 'Open session', retry: 'Retry', retryOf: 'Retry of an earlier run',
    noRuns: 'No agent tasks yet', noRunsNext: 'Evaluate a job or draft documents and tasks will appear here.', noMatch: 'No tasks with this status', autoRefresh: 'Refreshes every 5 seconds while a task is still running', filterLabel: 'Filter by status',
    actions: { promote_cv: 'Make the new CV revision the primary CV', delete_document_revision: 'Delete this document revision', delete_file: 'Delete this file' },
    pending: 'Awaiting decision', resolved: 'Resolved', approve: 'Approve', reject: 'Reject', expiresIn: 'Expires', openRun: 'View requesting task', digest: 'Change digest',
    approved: 'Approved', rejected: 'Rejected', expired: 'Expired', used: 'Used', noPending: 'No approvals waiting', noApprovals: 'No approval requests yet', noApprovalsNext: 'When an agent wants to make a significant change, the request appears here.',
    caps: { 'results:read': 'Read results', 'jobs:evaluate': 'Evaluate jobs', 'documents:draft': 'Draft documents' },
    grants: 'Issued access', noGrants: 'No external agents connected', noGrantsNext: 'Issue an access token so an MCP client or another agent can reach this project.',
    active: 'Active', expiredS: 'Expired', revoked: 'Revoked', expiresAt: 'Expires', revoke: 'Revoke', token: 'Access token', issue: 'Issue access token', issueIntro: 'Choose the permissions and lifetime of a token for an external agent.',
    capabilities: 'Permissions', expiry: 'Lifetime', h1: '1 hour', h24: '24 hours', d7: '7 days', create: 'Issue token', shownOnce: 'Your token',
    warning: 'Copy it now. It will not be shown again.', dismiss: 'Dismiss and clear from this page', needCap: 'Select at least one permission', id: 'Grant',
    connectTitle: 'Connect MCP / A2A', connectIntro: 'External MCP clients and A2A agents can use this project through the protocol listener. It is off by default; start it only when you need it.',
    startTitle: 'Start the listener', startNote: 'The app must be started with --enable-sharing for this port to open.',
    endpoints: 'Endpoints', mcp: 'MCP (streamable HTTP)', card: 'Agent card', a2a: 'A2A base URL',
    snippetTitle: 'MCP client config', snippetNote: 'Replace <ACCESS_TOKEN> with a token from the "Connected agents" tab. Never put a real token in a shared or committed file.',
    curlTitle: 'Fetch the agent card with curl', secNote: 'A token is a bearer credential: anyone holding it can use the project within its permissions. Keep it secret, set a short lifetime and revoke it when unused.',
  },
};
export type Copy = typeof copy.th;
