import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';

test('actual owner API persists project, CV, posting and separate sessions through reload', async ({ page }) => {
  test.setTimeout(120000);
  test.skip(!process.env.JSP_E2E_SESSION_FILE, 'requires isolated real backend launcher fixture');
  const launch = JSON.parse(await readFile(process.env.JSP_E2E_SESSION_FILE!, 'utf8'));
  await page.addInitScript(() => localStorage.setItem('ui.locale', 'en'));
  await page.goto(`/#owner-nonce=${encodeURIComponent(launch.nonce)}`);
  await page.getByRole('link', { name: 'Get started', exact: true }).click();
  await page.getByRole('link', { name: 'Create a project', exact: true }).last().click();
  await page.locator('#project-name').fill('Synthetic actual browser project');
  await page.locator('#project-goal').fill('Synthetic data analyst search');
  await page.getByRole('button', { name: 'Create a project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Profile and CV', exact: true })).toBeVisible();
  const projectId = new URL(page.url()).pathname.split('/')[3];
  await page.locator('#cv-text').fill('Synthetic Candidate\nData analyst. SQL and Python, three years. Bangkok.');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.locator('.revision-list')).toContainText('pasted-cv.txt', { timeout: 60000 });
  await page.goto(`/app/projects/${projectId}/jobs`);
  await page.locator('#job-title').fill('Synthetic Bangkok analyst');
  await page.locator('#job-description').fill('Synthetic role: Python, SQL and analysis in Bangkok.');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Synthetic Bangkok analyst', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Synthetic Bangkok analyst', exact: true }).click();
  await expect(page.getByTestId('job-description')).toContainText('Python, SQL and analysis in Bangkok.');
  await page.goto(`/app/projects/${projectId}/profile`);
  await page.locator('#session-title').fill('Second separate synthetic session');
  await page.getByRole('button', { name: 'New conversation', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Second separate synthetic session', exact: true })).toBeVisible();
  await expect(page.locator('#workflow-job')).toContainText('Synthetic Bangkok analyst');
  await expect(page.getByRole('button', { name: 'Start run', exact: true })).toBeDisabled();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Second separate synthetic session', exact: true })).toBeVisible();
  expect(new URL(page.url()).hash).toBe('');
  const stored = await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }));
  expect(stored).not.toContain('Synthetic Candidate');
  expect(stored).not.toContain(launch.nonce);
});
